module.exports = {
	lightTheme: {
		base: 'vs',
		inherit: true,
		rules: [{ background: 'fafafa' }],
		colors: {
			"foreground": "#85888c",
			"selection.background": "#f0eee4fd",
			"editor.background": "#fafafa",
			"editor.foreground": "#5c6066",
			"editor.selectionBackground": "#f0eee4",
			"editor.findMatchBackground": "#ff6a0033",
			"editor.findMatchHighlightBackground": "#ff6a0033",
			"editor.findRangeHighlightBackground": "#ff6a0033",
			"editor.lineHighlightBackground": "#f2f2f2",
			"editor.rangeHighlightBackground": "#f2f2f2",
			"editor.wordHighlightBackground": "#ff6a0033",
			"editor.wordHighlightStrongBackground": "#ff6a0033",
			"editorCursor.foreground": "#ff6a00",
			"editorWhitespace.foreground": "#d9d8d7",
			"editorIndentGuide.background": "#d9d8d7",
			"editorLineNumber.foreground": "#b20000",
			"editorSuggestWidget.background": "#ffffff",
			"editorSuggestWidget.border": "#e2e4e7",
			"editorSuggestWidget.selectedBackground": "#f5f5f5",
			"editorSuggestWidget.highlightForeground": "#ff6a00",
		}
	},
	darkTheme: {
		base: 'vs-dark',
		inherit: true,
		rules: [{ background: '0f1419'}],
		colors: {
			"foreground": "#515c66",
			"selection.background": "#253340fd",
			"editor.background": "#0f1419",
			"editor.foreground": "#e6e1cf",
			"editor.selectionBackground": "#253340",
			"editor.findMatchBackground": "#f2971833",
			"editor.findMatchHighlightBackground": "#f2971833",
			"editor.findRangeHighlightBackground": "#f2971833",
			"editor.lineHighlightBackground": "#151a1f",
			"editor.rangeHighlightBackground": "#151a1f",
			"editor.wordHighlightBackground": "#f2971833",
			"editor.wordHighlightStrongBackground": "#f2971833",
			"editorCursor.foreground": "#f29718",
			"editorWhitespace.foreground": "#35404c",
			"editorIndentGuide.background": "#35404c",
			"editorLineNumber.foreground": "#c0c0c0",
			"editorSuggestWidget.background": "#14191f",
			"editorSuggestWidget.border": "#1d242c",
			"editorSuggestWidget.selectedBackground": "#191f26",
			"editorSuggestWidget.highlightForeground": "#f29718",
		}
	}
};