libraries 		= []
library_paths 	= ''
cpp_defines 	= {}
cpp_paths       = ['include']
cpp_flags 		= ['-Wall', '-Wextra',
                   '-pedantic-errors',
                   '-Wcast-align', '-Wcast-qual', '-Wfloat-equal', '-Wpointer-arith',
                   '-Wctor-dtor-privacy', '-Wredundant-decls',
                   '-Wformat=2', '-Wmissing-format-attribute',
                   '-Wlogical-op', '-Wshadow', '-Wuseless-cast', # '-Wconversion', '-Wsign-conversion',
                   '-Wstrict-overflow=5', '-Wswitch-default', '-Winline', '-Wimplicit-fallthrough=5',
                   '-Wmissing-declarations', '-Wmissing-field-initializers', # '-Wmissing-include-dirs',
                   '-Wsuggest-final-types', '-Wsuggest-final-methods', '-Wsuggest-override',
                   '-Wundef', '-Wunused', '-Wuninitialized',
                   '-Wnull-dereference', '-Wpacked', # '-Wpadded',
                   '-Wzero-as-null-pointer-constant', '-Wmisleading-indentation',
                   '-Wdisabled-optimization']
cxx_flags 		= ['-std=c++17']

common = Environment()

common['CXX'] = 'g++-7'

common.Append(LIBS 			= libraries)
common.Append(LIBPATH 		= library_paths)
common.Append(CPPPATH       = cpp_paths)
common.Append(CPPDEFINES 	= cpp_defines)
common.Append(CPPFLAGS 		= cpp_flags)
common.Append(CXXFLAGS 		= cxx_flags)

# release = common.Clone()
# release.Append(CPPDEFINES=['RELEASE'])
# release.VariantDir('../build/release', '.', duplicate=0)
# release.VariantDir('../build/release/test', 'test', duplicate=0)

debug = common.Clone()
# debug.Append(CPPDEFINES=['DEBUG'], CCFLAGS=['-g'])
debug.Append(CCFLAGS=['-O1', '-march=native'])
debug.VariantDir('debug', 'src', duplicate=0)
debug.VariantDir('debug/tests', 'tests', duplicate=0)

debug.Program('debug/frisc-fnsim', ['debug/fnsim/frisc.cpp', 'debug/fnsim/fnsim.cpp'])

# debug.Program('debug/tests/common/structures_bitfield', ['debug/tests/common/test_structures_bitfield.cpp'])
