libraries 		= []
library_paths 	= ''
cpp_defines 	= {}
cpp_paths       = ['include']
cpp_flags 		= ['-Wall', '-Wextra']  #, '-Werror']
cxx_flags 		= ['-std=c++17']

common = Environment()

common['CXX'] = 'g++-7'

common.Append(LIBS 			= libraries)
common.Append(LIBPATH 		= library_paths)
common.Append(CPPPATH       = cpp_paths)
common.Append(CPPDEFINES 	= cpp_defines)
common.Append(CPPFLAGS 		= cpp_flags)
common.Append(CXXFLAGS 		= cxx_flags)

# release = common.Clone()
# release.Append(CPPDEFINES=['RELEASE'])
# release.VariantDir('../build/release', '.', duplicate=0)
# release_env.VariantDir('../build/release/test', 'test', duplicate=0)

debug = common.Clone()
debug.Append(CPPDEFINES=['DEBUG'], CCFLAGS=['-g'])
debug.VariantDir('debug', 'src', duplicate=0)

# debug.Program('../build/debug/core/functional-test', ['src/simulators/fnsim.cpp'])
debug.Program('debug/frisc-fnsim', ['debug/fnsim/frisc.cpp', 'debug/fnsim/fnsim.cpp'])
# debug.Program('frisc-hls', 'src/ls/frisc.cpp')
